---
# Source: kuberay-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuberay-operator
  namespace: sorami-lab-stack-kuberay
  labels:
    app.kubernetes.io/name: kuberay-operator
    helm.sh/chart: kuberay-operator-1.7.1
    app.kubernetes.io/instance: kuberay-operator
    app.kubernetes.io/managed-by: Helm
---
# Source: kuberay-operator/templates/ray_raycronjob_editor_role.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: raycronjob-editor-role
  labels:
    app.kubernetes.io/name: kuberay-operator
    helm.sh/chart: kuberay-operator-1.7.1
    app.kubernetes.io/instance: kuberay-operator
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ray.io
  resources:
  - raycronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ray.io
  resources:
  - raycronjobs/status
  verbs:
  - get

---
# Source: kuberay-operator/templates/ray_raycronjob_viewer_role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: raycronjob-viewer-role
  labels:
    app.kubernetes.io/name: kuberay-operator
    helm.sh/chart: kuberay-operator-1.7.1
    app.kubernetes.io/instance: kuberay-operator
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ray.io
  resources:
  - raycronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ray.io
  resources:
  - raycronjobs/status
  verbs:
  - get

---
# Source: kuberay-operator/templates/ray_rayjob_editor_role.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rayjob-editor-role
  labels:
    app.kubernetes.io/name: kuberay-operator
    helm.sh/chart: kuberay-operator-1.7.1
    app.kubernetes.io/instance: kuberay-operator
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ray.io
  resources:
  - rayjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ray.io
  resources:
  - rayjobs/status
  verbs:
  - get

---
# Source: kuberay-operator/templates/ray_rayjob_viewer_role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rayjob-viewer-role
  labels:
    app.kubernetes.io/name: kuberay-operator
    helm.sh/chart: kuberay-operator-1.7.1
    app.kubernetes.io/instance: kuberay-operator
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ray.io
  resources:
  - rayjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ray.io
  resources:
  - rayjobs/status
  verbs:
  - get

---
# Source: kuberay-operator/templates/ray_rayservice_editor_role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rayservice-editor-role
  labels:
    app.kubernetes.io/name: kuberay-operator
    helm.sh/chart: kuberay-operator-1.7.1
    app.kubernetes.io/instance: kuberay-operator
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ray.io
  resources:
  - rayservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ray.io
  resources:
  - rayservices/status
  verbs:
  - get

---
# Source: kuberay-operator/templates/ray_rayservice_viewer_role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rayservice-viewer-role
  labels:
    app.kubernetes.io/name: kuberay-operator
    helm.sh/chart: kuberay-operator-1.7.1
    app.kubernetes.io/instance: kuberay-operator
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ray.io
  resources:
  - rayservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ray.io
  resources:
  - rayservices/status
  verbs:
  - get

---
# Source: kuberay-operator/templates/role.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kuberay-operator
  labels:
    app.kubernetes.io/name: kuberay-operator
    helm.sh/chart: kuberay-operator-1.7.1
    app.kubernetes.io/instance: kuberay-operator
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - pods/status
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/proxy
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods/resize
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services/proxy
  verbs:
  - create
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates/status
  verbs:
  - get
- apiGroups:
  - cert-manager.io
  resources:
  - issuers
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  - httproutes
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ray.io
  resources:
  - rayclusters
  - raycronjobs
  - rayjobs
  - rayservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ray.io
  resources:
  - rayclusters/finalizers
  - raycronjobs/finalizers
  - rayjobs/finalizers
  - rayservices/finalizers
  verbs:
  - update
- apiGroups:
  - ray.io
  resources:
  - rayclusters/status
  - raycronjobs/status
  - rayjobs/status
  - rayservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

---
# Source: kuberay-operator/templates/rolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kuberay-operator
  labels:
    app.kubernetes.io/name: kuberay-operator
    helm.sh/chart: kuberay-operator-1.7.1
    app.kubernetes.io/instance: kuberay-operator
    app.kubernetes.io/managed-by: Helm
subjects:
- kind: ServiceAccount
  name: kuberay-operator
  namespace: sorami-lab-stack-kuberay
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kuberay-operator

---
# Source: kuberay-operator/templates/leader_election_role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kuberay-operator-leader-election
  namespace: sorami-lab-stack-kuberay
  labels:
    app.kubernetes.io/name: kuberay-operator
    helm.sh/chart: kuberay-operator-1.7.1
    app.kubernetes.io/instance: kuberay-operator
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update

---
# Source: kuberay-operator/templates/leader_election_role_binding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kuberay-operator-leader-election
  namespace: sorami-lab-stack-kuberay
  labels:
    app.kubernetes.io/name: kuberay-operator
    helm.sh/chart: kuberay-operator-1.7.1
    app.kubernetes.io/instance: kuberay-operator
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kuberay-operator-leader-election
subjects:
- kind: ServiceAccount
  name: kuberay-operator
  namespace: sorami-lab-stack-kuberay

---
# Source: kuberay-operator/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kuberay-operator
  namespace: sorami-lab-stack-kuberay
  labels:
    app.kubernetes.io/name: kuberay-operator
    helm.sh/chart: kuberay-operator-1.7.1
    app.kubernetes.io/instance: kuberay-operator
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kuberay-operator
    app.kubernetes.io/instance: kuberay-operator

---
# Source: kuberay-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberay-operator
  namespace: sorami-lab-stack-kuberay
  labels:
    app.kubernetes.io/name: kuberay-operator
    helm.sh/chart: kuberay-operator-1.7.1
    app.kubernetes.io/instance: kuberay-operator
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: kuberay-operator
      app.kubernetes.io/instance: kuberay-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kuberay-operator
        app.kubernetes.io/instance: kuberay-operator
        app.kubernetes.io/component: kuberay-operator
    spec:
      serviceAccountName: kuberay-operator
      containers:
        - name: kuberay-operator
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          image: "quay.io/kuberay/operator:v1.7.1"
          imagePullPolicy: IfNotPresent
          command:
            - /manager
          args:
            - --log-stdout-encoder
            - json
            - --log-file-encoder
            - json
            - --enable-leader-election=true
            - --enable-metrics=true
            - --reconcile-concurrency=1
            - --qps=100
            - --burst=200
            - --feature-gates=RayClusterStatusConditions=true,RayJobDeletionPolicy=true,RayMultiHostIndexing=true,RayServiceIncrementalUpgrade=true,RayCronJob=false,RayClusterMTLS=false,RayClusterNetworkPolicy=false,RayClusterHistoryServer=false
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
---
# Source: ray-cluster/templates/raycluster-cluster.yaml
apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: raycluster-kuberay
  namespace: sorami-lab-stack-kuberay
  labels:
    helm.sh/chart: ray-cluster-1.7.1
    app.kubernetes.io/instance: raycluster
    app.kubernetes.io/managed-by: Helm
spec:
  headGroupSpec:
    serviceType: ClusterIP
    template:
      metadata:
        labels:
          helm.sh/chart: ray-cluster-1.7.1
          app.kubernetes.io/instance: raycluster
          app.kubernetes.io/managed-by: Helm
      spec:
        containers:
        - name: ray-head
          image: rayproject/ray:2.52.0
          imagePullPolicy: IfNotPresent
          
          volumeMounts:
          - mountPath: /tmp/ray
            name: log-volume
          resources:
            limits:
              cpu: "1"
              memory: 5Gi
            requests:
              cpu: "1"
              memory: 5Gi
        volumes:
          - emptyDir: {}
            name: log-volume
  workerGroupSpecs:
  - groupName: workergroup
    replicas: 1
    minReplicas: 1
    maxReplicas: 5
    numOfHosts: 1
    template:
      metadata:
        labels:
          helm.sh/chart: ray-cluster-1.7.1
          app.kubernetes.io/instance: raycluster
          app.kubernetes.io/managed-by: Helm
      spec:
        containers:
        - name: ray-worker
          image: rayproject/ray:2.52.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /tmp/ray
            name: log-volume
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 1Gi
        volumes:
        - emptyDir: {}
          name: log-volume
---
# Source: vllm-stack/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "vllm-router-service-account"
  namespace: sorami-lab-stack-vllm

---
# Source: vllm-stack/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "vllm-secrets"
  namespace: sorami-lab-stack-vllm
type: Opaque
data:

---
# Source: vllm-stack/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "vllm-mistral-storage-claim"
  namespace: sorami-lab-stack-vllm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
---
# Source: vllm-stack/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "vllm-reader"
  namespace: sorami-lab-stack-vllm
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list", "patch"]

---
# Source: vllm-stack/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vllm-deployment-access-binding
  namespace: sorami-lab-stack-vllm
subjects:
  - kind: ServiceAccount
    name: vllm-router-service-account
    namespace: sorami-lab-stack-vllm
roleRef:
  kind: Role
  name: vllm-reader
  apiGroup: rbac.authorization.k8s.io

---
# Source: vllm-stack/templates/service-router.yaml
apiVersion: v1
kind: Service
metadata:
  name: "vllm-router-service"
  namespace: sorami-lab-stack-vllm
  labels:
    app.kubernetes.io/name: router
    app.kubernetes.io/instance: vllm
    app.kubernetes.io/component: router
    app.kubernetes.io/part-of: vllm-stack
    app.kubernetes.io/managed-by: helm
    environment: router
    release: router
spec:
  type: ClusterIP
  ports:
    - name: "router-sport"
      port: 80
      targetPort: 8000
      protocol: TCP
    - name: "lmcache-port"
      port: 9000
      targetPort: lmcache-port
      protocol: TCP
    
  selector:
    app.kubernetes.io/name: router
    app.kubernetes.io/instance: vllm
    app.kubernetes.io/component: router
    app.kubernetes.io/part-of: vllm-stack
    app.kubernetes.io/managed-by: helm
    environment: router
    release: router

---
# Source: vllm-stack/templates/service-vllm.yaml
apiVersion: v1
kind: Service
metadata:
  name: "vllm-mistral-engine-service"
  namespace: sorami-lab-stack-vllm
  labels:
    app.kubernetes.io/name: mistral
    app.kubernetes.io/instance: vllm
    app.kubernetes.io/component: serving-engine
    app.kubernetes.io/part-of: vllm-stack
    app.kubernetes.io/managed-by: helm
    environment: test
    release: test
spec:
  type: ClusterIP
  ports:
    - name: "service-port"
      port: 80
      targetPort: "container-port"
      protocol: TCP
    - name: zmq-port
      port: 55555
      targetPort: zmq-port
      protocol: TCP
    - name: ucx-port
      port: 9999
      targetPort: ucx-port
      protocol: TCP
    
  selector:
    model: "mistral"
    helm-release-name: "vllm"
    app.kubernetes.io/name: mistral
    app.kubernetes.io/instance: vllm
    app.kubernetes.io/component: serving-engine
    app.kubernetes.io/part-of: vllm-stack
    app.kubernetes.io/managed-by: helm
    environment: test
    release: test

---
# Source: vllm-stack/templates/deployment-router.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "vllm-deployment-router"
  namespace: sorami-lab-stack-vllm
  labels:
    app.kubernetes.io/name: router
    app.kubernetes.io/instance: vllm
    app.kubernetes.io/component: router
    app.kubernetes.io/part-of: vllm-stack
    app.kubernetes.io/managed-by: helm
    environment: router
    release: router
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: router
      app.kubernetes.io/instance: vllm
      app.kubernetes.io/component: router
      app.kubernetes.io/part-of: vllm-stack
      app.kubernetes.io/managed-by: helm
      environment: router
      release: router
  template:
    metadata:
      labels:
        app.kubernetes.io/name: router
        app.kubernetes.io/instance: vllm
        app.kubernetes.io/component: router
        app.kubernetes.io/part-of: vllm-stack
        app.kubernetes.io/managed-by: helm
        environment: router
        release: router
    spec:
      serviceAccountName: vllm-router-service-account
      containers:
      - name: router-container
        image: "lmcache/lmstack-router:latest"
        imagePullPolicy: "Always"
        env:
          - name: PYTHONHASHSEED
            value: "123"
          - name: LMCACHE_LOG_LEVEL
            value: "INFO"
        args:
          - "--host"
          - "0.0.0.0"
          - "--port"
          - "8000"
          - "--service-discovery"
          - "k8s"
          - "--k8s-namespace"
          - "sorami-lab-stack-vllm"
          - "--k8s-service-discovery-type"
          - "pod-ip"
          - "--k8s-label-selector"
          - environment=test,release=test
          - "--routing-logic"
          - "roundrobin"
          - "--engine-stats-interval"
          - "15"
          - "--request-stats-window"
          - "60"
        resources:
          limits:
            memory: 1000Mi
          requests:
            cpu: 400m
            memory: 1000Mi
        ports:
          - name: "router-port"
            containerPort: 8000
          - name: "lmcache-port"
            containerPort: 9000
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: router-port
          initialDelaySeconds: 30
          periodSeconds: 5
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: router-port
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: router-port
          initialDelaySeconds: 30
          periodSeconds: 5
